Add more unit placement overlays templates
Also make placement renderer unit conflict message more
helpful.

diff --git a/common/render.d/unit_placement b/common/render.d/unit_placement
--- a/common/render.d/unit_placement
+++ b/common/render.d/unit_placement
@@ -26,18 +26,20 @@ _render_placement_units ()
         fi
     fi
 
-    ((num_units<=num_machines)) || \
-        { echo "ERROR: more units requested ($num_units) that machines available ($num_machines) (template=$template_short)"; exit 1; }
+    if ((num_units>num_machines)); then
+        echo "ERROR: more units requested ($num_units) that machines available ($num_machines) (template=$template_short) - hint: add more compute nodes/units"
+        exit 1
+    fi
 
     # remove metadata
     sed -i "s/\.__UNITS__\.$num_units_key//" $template
     [ -z "$machine_offset_key" ] || sed -ri "/.+$machine_offset_key.*/d" $template
 
     # pick $num_units machines at random but preserve existing unit ids
-    local id_cache=$PLACEMENT_OVERLAYS_DIR/$template_short.units.machine.ids
+    local id_store=$PLACEMENT_OVERLAYS_DIR/$template_short.units.machine.ids
     local -A id_dict=()
     # load existing
-    [ -e "$id_cache" ] && while read line; do id_dict[$line]=0; done < $id_cache
+    [ -e "$id_store" ] && while read line; do id_dict[$line]=0; done < $id_store
     # fill gaps
     while ((${#id_dict[@]}<num_units)); do
         if [[ $placement_type == METAL ]]; then
@@ -46,14 +48,15 @@ _render_placement_units ()
             id=$(($RANDOM % num_machines))
         fi
         id_dict[$id]=0
-        ! [ -e "$id_cache" ] || ((${#id_dict[@]} > `wc -l $id_cache| awk '{print $1}'`)) || continue
-        echo $id >> $id_cache
+        # if we actually have a new id, add it to store
+        ! [ -e "$id_store" ] || ! `grep -qw "$id" $id_store` || continue
+        echo $id >> $id_store
     done
 
     local tmp_out=$PLACEMENT_OVERLAYS_DIR/$template_short.units.${placement_type,,}
     rm -f $tmp_out
     for ((i=1;i<=num_units;i++)); do
-        id=`sed "${i}q;d" $id_cache`
+        id=`sed "${i}q;d" $id_store`
         cat $placement_templates_dir/unit_${placement_type,,}.yaml| \
             sed -r -e "s/__MACHINE_ID__/$id/g" >> $tmp_out
     done
