Add k8s hyperconverged support
Resolves: #144

diff --git a/common/generate_bundle_base b/common/generate_bundle_base
--- a/common/generate_bundle_base
+++ b/common/generate_bundle_base
@@ -154,8 +154,17 @@ readarray -t application_list < <("$MOD_DIR/../tools/juju-bundle-applications.py
 # Generate placement overlay for use with MAAS provider
 if ${MASTER_OPTS[HYPERCONVERGED_DEPLOYMENT]}; then
     cp  $MOD_DIR/overlays/unit_placement/header.yaml.template $bundles_dir/unit-placement.yaml
-    # these two represent total machines since e.g. ceph is deployed on compute but compute and gateway are never colocated
-    num_placement_machines=$((${MOD_PARAMS[__NUM_NEUTRON_GATEWAY_UNITS__]}+${MOD_PARAMS[__NUM_COMPUTE_UNITS__]}))
+    if [[ $MOD_NAME = openstack ]]; then
+        # these two represent total machines since e.g. ceph is deployed on compute but compute and gateway are never colocated
+        num_placement_machines=$((${MOD_PARAMS[__NUM_NEUTRON_GATEWAY_UNITS__]}+${MOD_PARAMS[__NUM_COMPUTE_UNITS__]}))
+    elif [[ $MOD_NAME = kubernetes ]]; then
+        num_placement_machines=$((${MOD_PARAMS[__NUM_K8S_CONTROL_PLANE_UNITS__]}+${MOD_PARAMS[__NUM_K8S_WORKER_UNITS__]}))
+    elif [[ $MOD_NAME = ceph ]]; then
+        num_placement_machines=$((${MOD_PARAMS[__NUM_CEPH_OSD_UNITS__]}))
+    else
+        echo "ERROR: module '$MOD_NAME' does not yet have support for hyperconverged mode" 1>&2
+        exit 1
+    fi
     # detect all apps used and generate placement info by doing:
     #  * search for all app names in generated bundles/overlays
     #  * search unit_placement template with same name
