Add support for pinning charm revisions
This change adds a `--revision-info` option to import a bundle file in
YAML format and pin the charm revision deployed to the revisions from
the bundle file.  This option implies `--use-stable-charms`.

Other noteworthy changes include:

- Add `MOD_DIR` to make paths absolute so that the the generate script
  can be run from anywhere.
- Add a `--debug` option to debug the generate script.

Co-Authored-By: Edward Hope-Morley <edward.hope-morley@canonical.com>
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

diff --git a/common/generate_bundle_base b/common/generate_bundle_base
--- a/common/generate_bundle_base
+++ b/common/generate_bundle_base
@@ -20,7 +20,7 @@ elif [ -z "$MOD_PATH" ]; then
     echo "ERROR: no module name provided"
     exit 1
 elif has_opt --create-model && [ -z "${MASTER_OPTS[BUNDLE_NAME]}" ]; then
-    echo "ERROR: no --name provided so cannot create Juju model" 
+    echo "ERROR: no --name provided so cannot create Juju model"
     exit 1
 fi
 
@@ -45,7 +45,7 @@ if has_opt --list; then
     state_root=`get_bundle_state_root`
     if [ -d "$state_root" ]; then
         echo -e "Existing bundles:\n./b (default)"
-        find $state_root/* -maxdepth 0 -type d| egrep -v "/o$|resources" 
+        find $state_root/* -maxdepth 0 -type d| egrep -v "/o$|resources"
         echo ""
     else
         echo "There are currently no bundles."
@@ -81,6 +81,9 @@ has_opt --replay && finish
 # therefore no need to add parameters to this function and they should only
 # be defined in the custom generators.
 render () {
+    local charm_current
+    local charm_new
+
     # generic parameters only
     sed -i "s,__SERIES__,$series,g" $1
 
@@ -93,6 +96,17 @@ render () {
         vip=$vip_start_prefix.$((vip_start_suffix++))
         sed -i -r "s/__VIP__/$vip/g" $1
     fi
+
+    # Process charm revisions from bundle first.
+    for key in ${!MASTER_OPTS[@]}; do
+        prefix="CHARM_REVISIONS\."
+        if ! `echo $key| egrep -q "^$prefix"`; then
+            continue
+        fi
+        charm_current=${key##$prefix}
+        charm_new=${MASTER_OPTS[$key]}
+        sed -i -r "s,charm:.*${charm_current}$,charm: $charm_new," $1
+    done
 
     if has_opt --use-stable-charms; then
         sed -i -r 's,~openstack-charmers-next/,,g' $1
@@ -122,7 +136,7 @@ fi
 dtmp=`mktemp -d`
 template_path=$dtmp/`basename $MOD_BASE_TEMPLATE`
 bundle=${template_path%%.template}
-cp $MOD_BASE_TEMPLATE $bundle
+cp $MOD_DIR/$MOD_BASE_TEMPLATE $bundle
 render $bundle
 mv $bundle $bundles_dir
 [ -r "$INTERNAL_BUNDLE_CONFIG" ] && \
@@ -146,7 +160,7 @@ if ((${#MOD_OVERLAYS[@]})); then
     declare -a msgs=()
     for overlay in ${MOD_OVERLAYS[@]}; do
         [ "${overlays_deduped[$overlay]:-null}" = "null" ] || continue
-        cp overlays/$overlay $bundles_dir/o
+        cp $MOD_DIR/overlays/$overlay $bundles_dir/o
         ((${#overlay_opts[@]}==0)) && overlay_opts+=("")  # left padding
         overlay_opts+=( --overlay $bundles_dir/o/$overlay )
         render $bundles_dir/o/$overlay
diff --git a/common/helpers b/common/helpers
--- a/common/helpers
+++ b/common/helpers
@@ -7,16 +7,17 @@ declare -A MASTER_OPTS=(
     [CLOUD_NAME]=''
     [TARGET_RELEASE_NAME]=''
     [VIP_ADDR_START]=10.5.100.0
+    [CHARM_REVISIONS]=
 )
 DEFAULT_SERIES=bionic
 JUJU_VERSION="`juju --version 2>/dev/null| sed -r 's/^([[:digit:]\.]+).*/\1/g'`"
 JUJU_DEPLOY_OPTS=""
 
-. $LIB_COMMON/openstack_release_info
+. $MOD_DIR/common/openstack_release_info
 
 list_module_opts ()
 {
-    local script=`dirname $0`/pipeline/02configure
+    local script=$MOD_DIR/pipeline/02configure
 
     echo -e "\nMODULE OPTS:"
     grep __OPT__ $script| \
@@ -27,7 +28,7 @@ list_module_opts ()
 list_overlays ()
 {
     echo "Supported overlays:"
-    local script=`dirname $0`/pipeline/02configure
+    local script=$MOD_DIR/pipeline/02configure
     {
     grep -v __OPT__ $script| \
         sed -r 's/.+\s+(--[[:alnum:]\-]+\*?)[\)\|].*/\1/g;t;d'
@@ -37,7 +38,7 @@ list_overlays ()
 }
 
 _usage () {
-cat << EOF
+    cat << EOF
 USAGE: `basename $0` OPTIONS [OVERLAYS] [MODULE_OPTS]
 
 OPTIONS:
@@ -48,6 +49,8 @@ OPTIONS:
      --create-model
         Create Juju model using --name. Switches to model if it already
         exists. If this is not provided then the current Juju model is used.
+     --debug
+        Enable bash debug logging.
      --defaults
         Use module config defaults and don't ask for input.
      -h, --help
@@ -83,6 +86,10 @@ OPTIONS:
         By default the development (cs:~openstack-charmers-next) version of
         Openstack charms are used where available. Use this flag if you want to
         use the stable (released) charms i.e. cs:<charm>.
+    --revision-info
+        Path to a yaml-format bundle file that will be used to pin charms to
+        specific versions. This will automatically switch to using stable
+        charms (since versions are assumed to come from stable charms).
     --vip-addr-start
         Address a.b.c.d from which to start allocating virtual ip addresses used
         for deployed services. There must be enough addresses beyond this one to
@@ -102,7 +109,7 @@ OVERLAYS:
      that provide HA or scale-out services. See --list-overlays for
      available overlays.
 EOF
-list_module_opts
+    list_module_opts
 }
 
 update_master_opts ()
@@ -128,10 +135,9 @@ filter_master_opts ()
     # it may be required to raise an error for such args and for
     # this purpose we use a ERROR_ON_UNKNOWN_OPT global variable.
 
-    declare -a filtered=()
     local ERROR_ON_UNKNOWN_OPT=${ERROR_ON_UNKNOWN_OPT:-false}
 
-    while (($# > 0)); do 
+    while (($# > 0)); do
         case "$1" in
             --charm-channel)
                 MASTER_OPTS[CHARM_CHANNEL]="$2"
@@ -148,9 +154,9 @@ filter_master_opts ()
             --name|-n)
                 # give bundle set a name and store under named dir
                 MASTER_OPTS[BUNDLE_NAME]="${2%%:*}"
-		if [[ $2 =~ ":" ]]; then
+                if [[ $2 =~ ":" ]]; then
                     MASTER_OPTS[CLOUD_NAME]="${2##*:}"
-		fi
+                fi
                 shift
                 ;;
             --list-overlays)
@@ -179,6 +185,23 @@ filter_master_opts ()
             --vip-addr-start)
                 MASTER_OPTS[VIP_ADDR_START]="$2"
                 shift
+                ;;
+            --revision-info)
+                if (( $# < 2 )) || ! [ -r "$2" ]; then
+                    echo "Missing or invalid bundle file path"
+                    exit 1
+                fi
+                readarray -t temp < <("$MOD_DIR/../tools/parse-bundle.py" --get-charms $2)
+                for line in "${temp[@]}"; do
+                    read -a temp -r <<< ${line}
+                    MASTER_OPTS[CHARM_REVISIONS.${temp[0]}]=${temp[1]}
+                done
+                echo "INFO: enabling stable charms since version info provided."
+                CACHED_STDIN=( "${CACHED_STDIN[@]}" --use-stable-charms )
+                shift
+                ;;
+            --debug)
+                # stub
                 ;;
             -h|--help)
                 _usage
@@ -380,7 +403,7 @@ conflicts_with ()
     local opt="$1"
     shift
     for conflict in $@; do
-        `has_opt $conflict` || continue 
+        `has_opt $conflict` || continue
         echo "ERROR: you cannot use $opt with $conflict"
         exit 1
     done
@@ -417,7 +440,7 @@ has_min_release ()
 has_min_series ()
 {
     # Return true if provided series <= --series
-    # 
+    #
     # This is a tricky thing to do since series names do not increase
     # alphabetically (they wrapped between Zesty and Aardvark), so it takes
     # a bit more logic to get right.
@@ -432,7 +455,7 @@ has_min_series ()
     readarray -t ordered<<<`echo -n ${!lts_order[@]}| tr ' ' '\n'| sort -n| tr '\n' ' '`
     for o in ${ordered[@]}; do
         lts_arr+=( ${lts_order[$o]} )
-    done    
+    done
     readarray -t nonlts_arr<<<"`echo -n ${!nonlts[@]}| tr ' ' '\n' | sort`"
 
     # Now create full list
@@ -464,7 +487,7 @@ has_min_series ()
     for s in ${all_series[@]}; do
         if [ "$s" == "$series" ]; then
             [ "$s" == "$min_series" ] && return 0
-            $match && return 
+            $match && return
         elif [ "$s" == "$min_series" ]; then
             match=true
         fi
@@ -607,6 +630,11 @@ get_juju_model ()
         juju list-models 2>/dev/null| sed -r 's/^(.+)\* .+/\1/g;t;d'
     fi
 }
+
+if has_opt --debug; then
+    PS4='+(${BASH_SOURCE##*/}:${LINENO}) ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+    set -x
+fi
 
 pocket=`get_pocket`
 # get cli provided values or fallback to default
