Improve opt conflict checking
Provide an easy way to specify opt conflicts and
define them across existing opts.

Also ensure that using *-ha imports its corresponding
base overlay dependency so that it doesnt have to be
manually specified everytime e.g. --octavia-ha will now
also do --octavia automatically so that you don't have
to specify both.

Also fixes num_units on openstack-dashboard to use
NUM_HORIZON_UNITS.

diff --git a/common/helpers b/common/helpers
--- a/common/helpers
+++ b/common/helpers
@@ -367,13 +367,15 @@ has_opt ()
     return $?
 }
 
-check_opt_conflict ()
+conflicts_with ()
 {
-    local good=$1
-    local bad=$2
-    `has_opt $bad` || return 0
-    echo "ERROR: option $good conflicts with $bad"
-    exit 1
+    local opt="$1"
+    shift
+    for conflict in $@; do
+        `has_opt $conflict` || continue 
+        echo "ERROR: you cannot use $opt with $conflict"
+        exit 1
+    done
 }
 
 assert_min_release ()
