Add --pub-key for juju-lnav to copy key to units
juju-lnav can now be supplied with the path to a pub key
using the --pub-key flag. If ssh authentication to a host
fails, the script will then attempt to copy that pub key
to the unit's authorized_keys file before proceeding.

diff --git a/tools/juju-lnav b/tools/juju-lnav
--- a/tools/juju-lnav
+++ b/tools/juju-lnav
@@ -2,6 +2,7 @@
 
 set -e -u
 
+declare PUB_KEY=
 declare -A MACHINES=()
 declare -A CONTAINERS=()
 declare -A UNITS=()
@@ -46,23 +47,62 @@ expand_unit() {
     lnav_arguments=( "${lnav_arguments[@]}" "root@${ip_address}:${files}" )
 }
 
+can_ssh_connect() {
+    local ip_address="$1"
+    ssh \
+        -o ConnectTimeout=5 -o BatchMode=yes \
+        -o StrictHostKeyChecking=no \
+        "root@${ip_address}" true > /dev/null 2>&1
+}
+
 check_ssh_key() {
     local unit="$1"
     local ip_address="$2"
     echo "checking ssh key for ${ip_address}"
-    if ! ssh \
-        -o ConnectTimeout=5 -o BatchMode=yes \
-        -o StrictHostKeyChecking=accept-new \
-        "root@${ip_address}" true > /dev/null 2>&1; then
-      cat << END
-Unable to ssh into root@${ip_address}.
+    if can_ssh_connect "$ip_address"; then
+        return
+    fi
+
+    echo "Unable to ssh into root@${ip_address}." 1>&2
+
+    if [[ -n "$PUB_KEY" ]]; then
+        copy_pub_key "$unit" "$ip_address"
+    else
+        cat << END
 Please check that:
 1.  Your public key is in the authorized_hosts file of the root user on ${ip_address}
-    You can accomplish this via e.g.:
-        cat ~/.ssh/your_ssh_key.pub \\
-            | timeout 10 juju ssh ${unit} \\
-            -- sudo tee --append /root/.ssh/authorized_keys
+    You can accomplish this by rerunning this script with the --pub-key flag:
+    ./juju-lnav --pub-key ~/.ssh/id_rsa.pub UNIT:LOG
+
 2.  A different key is not set for this host in ~/.ssh/config,
+    e.g.
+
+    HostName ${ip_address}
+    IdentityFile ~/non_existent_key
+END
+        exit 1
+    fi
+}
+
+copy_pub_key() {
+    local unit="$1"
+    local ip_address="$2"
+    echo "copying ${PUB_KEY} to ${unit}'s authorized_keys"
+
+    if ! [[ -f "${PUB_KEY}" ]]; then
+        echo "${PUB_KEY} does not exist." 1>&2
+        exit 1
+    fi
+
+    cat "${PUB_KEY}" \
+        | timeout 10 juju ssh -q "$unit" \
+        -- sudo tee --append /root/.ssh/authorized_keys >/dev/null
+
+
+    if ! can_ssh_connect "$ip_address"; then
+        echo "Still unable to connect to ${ip_address}"
+        cat << END
+Please check that a different key is not set for this host in ~/.ssh/config,
     e.g.
 
     HostName ${ip_address}
@@ -147,8 +187,15 @@ Options:
 
 UNIT        is the name of the unit
 LOGFILES    is a regular shell GLOB
+
+--pub-key PATH      Key to copy to supplied UNIT's authorized_keys file
+                    if ssh authentication fails.
 EOF
             exit 0
+            ;;
+        --pub-key)
+            PUB_KEY="$2"
+            shift
             ;;
         *)
             if (( juju_info_loaded == 0 )); then
